
-- Inserir dados iniciais nas tabelas

IF (SELECT COUNT(*) FROM TBL_TAREFAS_STATUS) = 0
BEGIN
	INSERT INTO TBL_TAREFAS_STATUS VALUES
	('PENDENTE'),
	('EM ANDAMENTO'),
	('CONCLUÍDA')
END

IF (SELECT COUNT(*) FROM TBL_TAREFAS) = 0
BEGIN
	DECLARE @id_status_pendente INT = (SELECT ID_STATUS FROM TBL_TAREFAS_STATUS WHERE NOME = 'PENDENTE')
	DECLARE @id_status_andamento INT = (SELECT ID_STATUS FROM TBL_TAREFAS_STATUS WHERE NOME = 'EM ANDAMENTO')
	DECLARE @id_status_concluida INT = (SELECT ID_STATUS FROM TBL_TAREFAS_STATUS WHERE NOME = 'CONCLUÍDA')

	INSERT INTO TBL_TAREFAS VALUES
	('CRIAR REPOSITÓRIO', 'CRIAR REPOSITÓRIO NO GITHUB', GETDATE(), @id_status_concluida),
	('CRIAR PROJETO JAVA', 'CRIAR PROJETO JAVA COM SPRING BOOT VIA SPRING INICIALIZAR', GETDATE(), @id_status_concluida),
	('CRIAR SCRIPT SQL ESTRUTURA', 'CRIAR SCRIPT SQL DA ESTRUTURA DAS TABELAS', GETDATE(), @id_status_concluida),
	('CRIAR SCRIPT SQL DADOS INICIAIS', 'CRIAR SCRIPT SQL PARA DEFINICAO DOS STATUS E TAREFAS INICIAIS', GETDATE(), @id_status_andamento),
	('MAPEAR TABELAS', 'MAPEAR TABELAS NA APLICAÇÃO COM SPRING JPA', GETDATE(), @id_status_pendente),
	('CRIAR CRUD', 'CRIAR ENDPOINTS NA APLICAÇÃO PARA CRIAR, LISTAR, EDITAR E EXCLUIR TAREFAS', GETDATE(), @id_status_pendente),
	('CRIAR AMBIENTES EM NUVEM', 'CRIAR AMBIENTES DE DEV, QA E PROD EM ALGUMA NUVEM (AZURE, GCP OU AWS)', GETDATE(), @id_status_pendente),
	('CRIAR AUTOMATIZAÇÃO', 'CRIAR ESTEIRAS DE CI/CD COM JENKINS OU GITHUB ACTIONS', GETDATE(), @id_status_pendente),
	('SQL SERVER NO CI/CD', 'ANALISAR POSSIBILIDADE DE CONFIGURAR O SQL SERVER NO CI/CD TAMBÉM', GETDATE(), @id_status_pendente)
END












