name: CI/CD to Azure

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v1
        with:
          java-version: '21'

      - name: Build with Maven
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/develop" ]]; then
            mvn clean package -DskipTests -Dspring.profiles.active=dev
          fi
        working-directory: ./api-gerenciador-de-tarefas

      - name: List target directory
        run: ls -l ./api-gerenciador-de-tarefas/target

      - name: Upload JAR as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-jar
          path: ./api-gerenciador-de-tarefas/target/api-gerenciador-de-tarefas-0.0.1-SNAPSHOT.jar

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download JAR Artifact
        uses: actions/download-artifact@v4
        with:
          name: my-jar

      - name: List current directory
        run: ls -la

      - name: Debug variables
        run: |
          echo "App Name: ${{ github.ref == 'refs/heads/develop' && 'desafiojavadev' }}"
          echo "Publish Profile: ${{ github.ref == 'refs/heads/develop' && secrets.AZURE_WEBAPP_PUBLISH_PROFILE_DEV }}" 

      - name: Deploy to Azure
        uses: Azure/webapps-deploy@v2
        with:
          app-name: ${{ github.ref == 'refs/heads/develop' && 'desafiojavadev' }}
          publish-profile: ${{ github.ref == 'refs/heads/develop' && secrets.AZURE_WEBAPP_PUBLISH_PROFILE_DEV }}
          package: 'api-gerenciador-de-tarefas-0.0.1-SNAPSHOT.jar'
