name: CI/CD to Azure

on:
  push:
    branches:
      - develop
      - 'release/**'
      - 'main' 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v1
        with:
          java-version: '21'

      - name: Build with Maven
        run: mvn clean package -DskipTests
        working-directory: ./api-gerenciador-de-tarefas

      - name: List target directory
        run: ls -l ./api-gerenciador-de-tarefas/target

      - name: Upload JAR as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-jar
          path: ./api-gerenciador-de-tarefas/target/api-gerenciador-de-tarefas-0.0.1-SNAPSHOT.jar

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download JAR Artifact
        uses: actions/download-artifact@v4
        with:
          name: my-jar

      - name: List current directory
        run: ls -la

      - name: Deploy to Azure
        uses: Azure/webapps-deploy@v2
        with:
          app-name: api-gerenciador-de-tarefas
          publish-profile: ${{ github.ref == 'refs/heads/develop' && secrets.AZURE_WEBAPP_PUBLISH_PROFILE_DEV || github.ref == 'refs/heads/main' && secrets.AZURE_WEBAPP_PUBLISH_PROFILE_PROD || startsWith(github.ref, 'refs/heads/release/') && secrets.AZURE_WEBAPP_PUBLISH_PROFILE_QAS }}
          package: 'api-gerenciador-de-tarefas-0.0.1-SNAPSHOT.jar'
