name: CI/CD to Azure

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v1
        with:
          java-version: '21'

      - name: Build with Maven
        run: mvn clean package -DskipTests
        working-directory: ./api-gerenciador-de-tarefas

      - name: List target directory
        run: ls -l ./api-gerenciador-de-tarefas/target

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to Azure
        uses: Azure/webapps-deploy@v2
        with:
          app-name: ${{ github.ref == 'refs/heads/develop' && 'desafiojavadev' }}
          publish-profile: ${{ github.ref == 'refs/heads/develop' && secrets.AZURE_WEBAPP_PUBLISH_PROFILE_DEV }}
          package: './api-gerenciador-de-tarefas/target/*.jar'
